/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


public class ContentImpl extends de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentTypeImpl implements de.mgpit.oracle.reports.plugin.destination.cdm.schema.Content
{
   public ContentImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("content", "", ownerDoc); 
   }

   public ContentImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public ContentImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
