/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


public class CdmdocImpl extends de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocTypeImpl implements de.mgpit.oracle.reports.plugin.destination.cdm.schema.Cdmdoc
{
   public CdmdocImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("cdmdoc", "", ownerDoc); 
   }

   public CdmdocImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public CdmdocImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
