//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.08 at 09:56:05 CEST 
//


package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


/**
 * Java content class for cdmdoc complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="cdmdoc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}content"/>
 *       &lt;/sequence>
 *       &lt;attribute name="unifier" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CdmdocType {


    java.lang.String getUnifier();

    void setUnifier(java.lang.String value);

    de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentType getContent();

    void setContent(de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentType value);

}
