//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.08 at 09:56:05 CEST 
//


package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


/**
 * Java content class for cdmdoc element declaration.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;element name="cdmdoc" type="{}cdmdoc"/>
 * </pre>
 * 
 */
public interface Cdmdoc
    extends javax.xml.bind.Element, de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocType
{


}
