/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


public class ContentTypeImpl extends oracle.xml.jaxb.JaxbNode implements de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentType
{
   public ContentTypeImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("content", "", ownerDoc); 
   }

   public ContentTypeImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public ContentTypeImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setLength(int value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printInt(value);
      super.setJaxbElement("length", "", lexval, 0);
   }

   public int getLength()
   {
      java.lang.String lexval = super.getJaxbElement("length", "", 0);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseInt(lexval);
   }

   public void setProperties(de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType value)
   {
      super.setElement("properties", "", (oracle.xml.jaxb.JaxbNode)value, 1);
   }

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType getProperties()
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesTypeImpl obj = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesTypeImpl(getOwnerDocument());
      return (de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType) super.getElement("properties", "", (oracle.xml.jaxb.JaxbNode)obj, 1);
   }

   public void setData(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbElement("data", "", lexval, 2);
   }

   public java.lang.String getData()
   {
      java.lang.String lexval = super.getJaxbElement("data", "", 2);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("length") && namespace.equals(""))
            {
               super.setNodeArrayValue(0, n);
            }

         }
         if (name != null)
         {
            if (name.equals("properties") && namespace.equals(""))
            {
               super.setNodeArrayValue(1, n);
            }

         }
         if (name != null)
         {
            if (name.equals("data") && namespace.equals(""))
            {
               super.setNodeArrayValue(2, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   static final Object[] _ContentType = 
   {"length", "properties", "data"};

   protected Object[] getSchemaObject()
   {
      return _ContentType;
   }

}
