/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


public interface ContentType
{
   public void setLength(int value);

   public int getLength();

   public void setProperties(de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType value);

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType getProperties();

   public void setData(java.lang.String value);

   public java.lang.String getData();

}

