/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


public class ObjectFactory 
{
   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocType createCdmdocType()
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocType elem = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocTypeImpl(ownerDocument);
      return elem;
   }

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyType createPropertyType(java.lang.String value)
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyType elem = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyTypeImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyType createPropertyType()
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyType elem = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyTypeImpl(ownerDocument);
      return elem;
   }

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType createPropertiesType()
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType elem = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesTypeImpl(ownerDocument);
      return elem;
   }

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentType createContentType()
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentType elem = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.ContentTypeImpl(ownerDocument);
      return elem;
   }

   public de.mgpit.oracle.reports.plugin.destination.cdm.schema.Cdmdoc createCdmdoc()
   {
      de.mgpit.oracle.reports.plugin.destination.cdm.schema.Cdmdoc elem = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocImpl(ownerDocument);
      return elem;
   }

   public Object newInstance (Class javaContentInterface) throws javax.xml.bind.JAXBException
   {
      Object newInstance = null;
      java.lang.String elemName = javaContentInterface.getName();
      try
      {
         if (elemName.equals("de.mgpit.oracle.reports.plugin.destination.cdm.schema.Cdmdoc"))
         {
            newInstance = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocImpl(ownerDocument);
            return newInstance;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.JAXBException(e.toString());
      }
      return null;
   }

   public Object getProperty(String name)
   {
      return null;
   }

   public void setProperty(String name, Object value)
   {
   }

   public Object unmarshal(org.w3c.dom.Node node) throws javax.xml.bind.UnmarshalException
   {
      java.lang.String elemName = node.getLocalName();
      try
      {
         if (elemName.equals("cdmdoc"))
         {
            de.mgpit.oracle.reports.plugin.destination.cdm.schema.Cdmdoc unode = 
                 new de.mgpit.oracle.reports.plugin.destination.cdm.schema.CdmdocImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.UnmarshalException(e.toString());
      }
      return null;
   }

   public Object getSchemaLocation() throws Exception
   {
      return new java.io.File("H:/workspace/ReportsDestinations/src/payload/java/de/mgpit/oracle/reports/plugin/destination/cdm/schema/cdmdoc.xsd").toURL();
   }

   private oracle.xml.parser.v2.XMLDocument ownerDocument = 
        new oracle.xml.parser.v2.XMLDocument();

}
