/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package de.mgpit.oracle.reports.plugin.destination.cdm.schema;


public class PropertiesTypeImpl extends oracle.xml.jaxb.JaxbNode implements de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertiesType
{
   public PropertiesTypeImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("properties", "", ownerDoc); 
   }

   public PropertiesTypeImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public PropertiesTypeImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public java.util.List getProperty()
   {
      return (java.util.List)super.getList("property", "", this, 0);
   }

   public Object createJaxbNode(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name = node.getLocalName();
      java.lang.String namespace = node.getNamespaceURI();
      if (namespace == null)
         namespace = "";

      if (name.equals("property") && namespace.equals(""))
      {
         de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyTypeImpl obj = new de.mgpit.oracle.reports.plugin.destination.cdm.schema.PropertyTypeImpl((oracle.xml.parser.v2.XMLElement)node);
         return obj;
      }

      return null;
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("property") && namespace.equals(""))
            {
               super.setNodeVectorValue("property", "", this, 0, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   static final Object[] _Property = 
   {};

   static final Object[] _PropertiesType = 
   {_Property };

   protected Object[] getSchemaObject()
   {
      return _PropertiesType;
   }

}
